### ISSUE TITLE
MinGit may be lacking LFS support

### ISSUE THREAD

**Issue by dpogue** [Hoikas/GetUru#2]
Reported via OpenUru Discord, where the initial git clone works but getting the asset files fails due to LFS not being available. If the full Git for Windows is installed, the issue goes away (presumably because it's no longer using MinGit).

![Screenshot_45](https://github.com/user-attachments/assets/bbfdece0-3e97-4895-b54a-f6a7e02b006c)

**Comment by dpogue** [comment]
It sounds like one option is to download Git LFS for Windows separately from https://github.com/git-lfs/git-lfs/releases

That's supposed to work with MinGit.

**Comment by Hoikas** [comment]
Should be fixed by 5c4d236c2306cca107f1c27ae39249586a393665
